projeto_final/Hortagram/Web/Models/FotoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class FotoViewModel
    {

        public FotoViewModel()
        {
            this.USUARIO1 = new HashSet<UsuarioViewModel>();
        }

        public int FOTO_ID { get; set; }
        public int USUARIO_ID { get; set; }
        public string FOTO_URL { get; set; }
        [Display(Name = "Comentário")]
        public string CAPTION { get; set; }

        public virtual UsuarioViewModel USUARIO { get; set; }

        public virtual ICollection<UsuarioViewModel> USUARIO1 { get; set; }
    }
}

projeto_final/Hortagram/Web/Controllers/FotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Web.Business;
using Web.Models;

namespace Web.Controllers
{
    public class FotoController : Controller
    {
        // GET: Foto
        public ActionResult Index()
        {
            return View();
        }

        // GET: Foto/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Foto/Create
        public async Task<ActionResult> Create()
        {
            FotoViewModel newFoto = new FotoViewModel();

            newFoto.USUARIO_ID = await Utils.UserId();

            return View(newFoto);
        }

        // POST: Foto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FotoViewModel newFoto)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    if (Request.Files.Count > 0)
                    {
                        var file = Request.Files[0];

                        if (file.FileName != null && file.ContentLength > 0)
                        {
                            newFoto.FOTO_URL = Blob.UploadBlob(file);
                        }
                    }

                    //POST API

                    await Photo.Publish(newFoto);

                    return RedirectToAction("Index", "Timeline");

                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Foto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Foto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Foto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Foto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

projeto_final/Hortagram/Web/Views/Foto/Create.cshtml
@model Web.Models.FotoViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Publicar</h2>


@using (Html.BeginForm("Create", "Foto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.USUARIO_ID, new { htmlAttributes = new { @class = "form-control" } })

        <div class="form-group">
            <div class="col-md-6 col-md-offset-3">
                <img id="preview" src="@Html.DisplayFor(model => model.FOTO_URL)" class="img-responsive" style="height: auto; display: inline-block" />
                <p id="filename"></p>
            </div>
            <div class="col-md-6 col-md-offset-3">
                <label for="file" class="control-label"></label>
 
                <label class="btn btn-block btn-primary">
                    Selecione uma foto <input type="file" name="file" id="file" style="display:none;" />
                </label>
            </div>
            @Html.HiddenFor(model => model.FOTO_URL, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CAPTION, htmlAttributes: new { @class = "col-md-6 col-md-offset-3" })
            <div class="col-md-6 col-md-offset-3">
                @Html.TextAreaFor(model => model.CAPTION, new { @maxlength = 255, @rows = 5, @cols = 10, @class = "form-control form-control-lg", @style = "width: 100%; max-width: 100%" } )
                @Html.ValidationMessageFor(model => model.CAPTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6 text-right">
                <input type="submit" value="Publicar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Timeline", "Index")
</div>


<script>

    var filename = $('#filename');

    $('input[type=file]').change(function () {

        var file = $(this).val();

        console.log(file);
        console.log(filename);

        filename[0].textContent = file;
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}