projeto_final/Hortagram/Web/Models/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class UsuarioViewModel
    {
        public UsuarioViewModel()
        {
            this.FOTO = new HashSet<FotoViewModel>();
            this.FOTO1 = new HashSet<FotoViewModel>();
            this.USUARIO1 = new HashSet<UsuarioViewModel>();
            this.USUARIO2 = new HashSet<UsuarioViewModel>();
        }

        public int USUARIO_ID { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string FOTO_URL { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public string ANIVERSARIO { get; set; }


        public virtual ICollection<FotoViewModel> FOTO { get; set; }

        public virtual ICollection<FotoViewModel> FOTO1 { get; set; }

        public virtual ICollection<UsuarioViewModel> USUARIO1 { get; set; }

        public virtual ICollection<UsuarioViewModel> USUARIO2 { get; set; }
    }
}

projeto_final/Hortagram/Web/Controllers/TimelineController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Web.Business;
using Web.Models;

namespace Web.Controllers
{
    public class TimelineController : Controller
    {
        // GET: Timeline
        public async Task<ActionResult> Index()
        {

            string access_token = Session["access_token"]?.ToString();
            string userName = Session["userName"].ToString();

            int userId = await Utils.UserId();

            TimelineViewModel timeline = new TimelineViewModel();

            if (!string.IsNullOrEmpty(access_token))
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Const.ServiceUrl);
                    client.DefaultRequestHeaders.Accept.Clear();

                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", $"{access_token}");

                    var response = await client.GetAsync("/api/Usuarios/" + userId);

                    //var response = await client.GetAsync("/api/Usuarios/1");

                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();

                        UsuarioViewModel user = new UsuarioViewModel();

                        user = JsonConvert.DeserializeObject<UsuarioViewModel>(responseContent);

                        timeline.Usuario = user;
                        timeline.FotosAmigos = await Business.User.FotosAmigos(userId);
                        
                        timeline.FotosAmigos = timeline.FotosAmigos.Reverse().ToList();
                        timeline.Seguidores = user.USUARIO2.ToList();
                        timeline.Seguindo = user.USUARIO1.ToList();

                        ViewBag.FullName = user.NOME + " " + user.SOBRENOME;
                        ViewBag.Uid = userId;
                        ViewBag.Url = Const.ServiceUrl;

                        // Trabalhar Aqui

                        return View(timeline);
                    }

                    return View("Error");
                }
            }

            return RedirectToAction("Login", "Account", null);
        }



        public async Task<ActionResult> Friend(int id)
        {

            string access_token = Session["access_token"]?.ToString();
            string userName = Session["userName"].ToString();

            int userId = id;

            TimelineViewModel timeline = new TimelineViewModel();

            if (!string.IsNullOrEmpty(access_token))
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Const.ServiceUrl);
                    client.DefaultRequestHeaders.Accept.Clear();

                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", $"{access_token}");

                    var response = await client.GetAsync("/api/Usuarios/" + userId);

                    //var response = await client.GetAsync("/api/Usuarios/1");

                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();

                        UsuarioViewModel user = new UsuarioViewModel();

                        user = JsonConvert.DeserializeObject<UsuarioViewModel>(responseContent);

                        timeline.Usuario = user;
                        timeline.FotosAmigos = await Business.User.FotosAmigos(userId);

                        timeline.FotosAmigos = timeline.FotosAmigos.Reverse().ToList();
                        timeline.Seguidores = user.USUARIO2.ToList();
                        timeline.Seguindo = user.USUARIO1.ToList();

                        ViewBag.FullName = user.NOME + " " + user.SOBRENOME;
                        ViewBag.Uid = userId;
                        ViewBag.Url = Const.ServiceUrl;

                        // Trabalhar Aqui

                        return View(timeline);
                    }

                    return View("Error");
                }
            }

            return RedirectToAction("Login", "Account", null);
        }
    }
}

projeto_final/Hortagram/Web/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Web.Business;
using Web.Models;


namespace Web.Controllers
{
    public class UsuariosController : Controller
    {
        // GET: Usuarios
        public async Task<ActionResult> Index()
        {
            List<UsuarioViewModel> usuarios = await Business.User.GetAll();
            ViewBag.Uid = await Utils.UserId();
            ViewBag.Url = Const.ServiceUrl;
            return View(usuarios);
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Usuarios/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Usuarios/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

projeto_final/Hortagram/Web/Views/Usuarios/Index.cshtml
@model IEnumerable<Web.Models.UsuarioViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><i class="far fa-compass"></i> Explorer</h2>
@Html.ActionLink("Voltar", "Index", "Timeline")
<hr />
<!--<p>
    @Html.ActionLink("Create New", "Create")
</p>-->



@foreach (var item in Model)
{

    <div class="col-md-4">

        <div class="thumbnail" style="margin-bottom:16px; padding: 16px 0">
            <img src="@item.FOTO_URL" alt="@item.NOME @item.SOBRENOME" style="width: 100px; height: 100px;" class="img-responsive img-circle" />

            <div class="caption">
                <p class="text-center"><b>@item.NOME @item.SOBRENOME</b></p>
                
                
                @{bool follow = false;}

                @foreach (var u in item.USUARIO2)
                {

                    if(u.USUARIO_ID == @ViewBag.Uid)
                    {
                        follow = true;
                    }
                }

                @if(follow == true)
                {
                    <a href="javascript:;" class="btn btn-block btn-info">Seguindo</a> 
                } else { 
                    <a href="javascript:;" class="btn-seguir btn btn-block btn-primary" data-url="@ViewBag.Url" data-uidm="@ViewBag.Uid" data-uids="@item.USUARIO_ID">Seguir</a>
                }
                
                <p><a href="/Perfil/Friend/@item.USUARIO_ID" class="btn btn-block btn-link">Visitar Perfil</a></p>
            </div>
        </div>


    </div>

}

<div class="clearfix"></div>

<script type="text/javascript">


    $(".btn-seguir").click(function () {

        var url = this.dataset.url;
        var uidm = this.dataset.uidm;
        var uids = this.dataset.uids;

        var apiUrl = url + "api/Follow?uidm=" + uidm + "&uids=" + uids;
        var self = this;
        
        $.ajax({
            method: "POST",
            url: apiUrl,
            crossDomain: true,
            headers: {
                "Access-Control-Allow-Origin": "*"
            },
            success: function (response) {
                console.log("sucesso!");
                console.log(self);

                self.setAttribute('onclick', 'javascript: void();');
                self.classList.remove("btn-seguir");
                self.classList.remove("btn-primary");
                self.classList.add("btn-info");
                self.textContent = "Seguindo";
                
            },
            failure: function (response) {
                console.log(response.responseText);
            },
            error: function (response) {
                console.log(response.responseText);
            }
        });
        
    });
     
</script>